line-length = 100
target-version = "py310"

select = ["ALL"]
ignore = [
    "ANN",
    "ARG",
    "D",
    "E501",
    "F401",
    "PL",
    "S",
    "BLE001",
    "TRY003",
]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101", "PLR2004"]
"conftest.py" = ["PT003"]